CREATE TABLE IF NOT EXISTS full_urls (
  ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
  MD5 BINARY(16)    NOT NULL UNIQUE,
  URL VARCHAR(2048) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS short_urls (
  SHORT_URL VARCHAR(12) UNIQUE,
  URL_ID    BIGINT
);